blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "article"

urlpatterns = [
    path('articles/dashboard/', views.dashboard, name="dashboard"),
    path('articles/addarticle/', views.addArticle, name="addarticle"),
    path('articles/article/<int:id>', views.detail, name="detail"),
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('about/', views.about, name="about"),
    path('user/', include("user.urls")),
    path('articles/update/<int:id>', views.updateArticle, name="update"),
    path('articles/delete/<int:id>', views.deleteArticle, name="delete"),
    path('articles/', views.articles, name="articles"),
    path('articles/comment/<int:id>', views.addComment, name="comment"),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from .import views
app_name="user"
urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Article(models.Model):
    author = models.ForeignKey(
        "auth.User", on_delete=models.CASCADE, verbose_name="Yazar")
    title = models.CharField(max_length=50, verbose_name="Baslik")
    content = RichTextField()
    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name="Olusturulma Tarihi")
    article_image = models.FileField(
        blank=True, null=True, verbose_name="Makaleye Fotograf Ekle")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, verbose_name="Makale", related_name="comments")
    comment_author = models.CharField(max_length=50, verbose_name="Isim")
    comment_content = models.CharField(max_length=200, verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content

    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article
class ArticleForm(forms.ModelForm):
    class Meta:
        model=Article
        fields=["title","content","article_image"]

user/forms.py
from django import forms
class LoginForm(forms.Form):
    username=forms.CharField(label="Kullanici Adi")
    password=forms.CharField(label="Parola",widget=forms.PasswordInput)
class RegisterForm(forms.Form):
    username=forms.CharField(max_length=50,label="Kullanici Adi")
    password=forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm=forms.CharField(max_length=20,label="Parolayi Dogrula",widget=forms.PasswordInput)
    def clean(self):
        username=self.cleaned_data.get("username")
        password=self.cleaned_data.get("password")
        confirm=self.cleaned_data.get("confirm")
        if password and confirm and password!=confirm:
            raise forms.ValidationError("Parola eslesmiyor")
        values= {
        "username":username,
        "password":password
        }
        return values

article/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, reverse
from .forms import ArticleForm
from django.contrib import messages
from .models import Article, Comment
from django.contrib.auth.decorators import login_required


def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains=keyword)
        return render(request, "articles.html", {"articles": articles})
    articles = Article.objects.all()
    return render(request, "articles.html", {"articles": articles})


def index(request):
    return render(request, "index.html")


def about(request):
    return render(request, "about.html")


@login_required(login_url="user:login")
def dashboard(request):
    articles = Article.objects.filter(author=request.user)
    context = {
        "articles": articles
    }
    return render(request, "dashboard.html", context)


@login_required(login_url="user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Makale Basariyla Olusturuldu")
        return redirect("dashboard")
    return render(request, "addarticle.html", {"form": form})


def detail(request, id):
    # article=Article.objects.filter(id=id).first()
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    return render(request, "detail.html", {"article": article, "comments": comments})


@login_required(login_url="user:login")
def updateArticle(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None,
                       request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Makale Basariyla Guncellendi")
        return redirect("dashboard")
    return render(request, "update.html", {"form": form})


@login_required(login_url="user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request, "Makale Basariyla Silindi")
    return redirect("dashboard")


def addComment(request, id):
    article = get_object_or_404(Article, id=id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author=comment_author,
                             comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse('detail', kwargs={"id": id}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
def register(request):
    form=RegisterForm(request.POST or None)
    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")
        newUser=User(username=username)
        newUser.set_password(password)
        newUser.save()                  
        login(request,newUser)
        messages.info(request,"Basariyla Kayit Oldunuz...")
        return redirect("index")
    context={
            "form":form
        }
    return render(request,"register.html",context)
    """if request.method=="POST":
        form=RegisterForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get("username")
            password=form.cleaned_data.get("password")
            newUser=User(username=username)
            newUser.set_password(password)
            newUser.save()
            login(request,newUser)
            return redirect("index")
        context={
            "form":form
        }
        return render(request,"register.html",context)
    else:
        form=RegisterForm()
        context={
            "form":form
        }
        return render(request,"register.html",context)"""
def loginUser(request):
    form=LoginForm(request.POST or None)
    context={
        "form":form
    }
    if form.is_valid():
        username=form.cleaned_data.get("username")
        password=form.cleaned_data.get("password")
        user=authenticate(username=username,password=password)
        if user is None:
            messages.info(request,"Kullanici adi ve ya parola hatali...")
            return render(request,"login.html",context)
        messages.success(request,"Basariyla Giris Yaptiniz")
        login(request,user)
        return redirect("index")
    return render(request,"login.html",context)
def logoutUser(request):
    logout(request)
    messages.success(request,"Basariyla Cikis Yaptiniz")
    return redirect("index")

blog/templates/about.html
{% extends "layout.html" %}
{% block body %}
    <h3>Hakkinda</h3>
    <hr>
    <p>Umidvaram birgun hersey yaxsi olar</p>
{% endblock  %}

blog/templates/addarticle.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makale olustur</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media }}
                {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-danger">Makale ekle</button>
            </form>
        </div>
    </div>
{% endblock body %}

blog/templates/articles.html
{% extends "layout.html" %}
{% block body %}
    <div class="row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-10 offset-md-3">
            <div class="col-lg-8">
                <form >
                    {% csrf_token %}
                    <input type="text"
                           name="keyword"
                           class="input-sm"
                           maxlength="64"
                           placeholder="Ara...">
                    <button type="submit" class="btn btn-danger">Ara</button>
                </form>
            </div>
        </div>
    </div>
    {% if articles %}
        {% for article in articles %}
            <!DOCTYPE html>
            <html lang="en">
                <head>
                    <meta charset="UTF-8">
                    <meta http-equiv="X-UA-Compatible" content="IE=edge">
                    <meta name="viewport" content="width=device-width, initial-scale=1.0">
                    <title>Document</title>
                    <link rel="stylesheet"
                          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
                    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
                    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
                    <title>Document</title>
                    <link rel="stylesheet"
                          href="C:/Users/Intelpoint/Desktop/bootsrap/bootstrap.min.css.map">
                    <link rel="stylesheet"
                          href="C:/Users/Intelpoint/Desktop/bootsrap/css/all.css">
                    <link rel="stylesheet" href="C:/Users/Intelpoint/Desktop/bootsrap/blog.css">
                </head>
                <body>
                    <div class="container">
                        <div class="row border-bottom">
                            <div class="col-md-6 offset-md-3">
                                <div class="col-10">
                                    <div class="col-lg-8">
                                        <a href="{% url 'detail' article.id %}">
                                            <h2>{{ article.title }}</h2>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div
                        <div class="container">
                            <div class="col-md-6 offset-md-3">
                                <p class="lead">{{ article.author.username }} tarafindan yayinlandi</p>
                            </div>
                            <div class="col-md-6 offset-md-60">
                                {% if article.article_image %}
                                    <a href="{% url 'detail' article.id %}">
                                        <img class="img-responsive" src="{{ article.article_image.url }}" alt="...">
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container mt-3">
                <div class="row">
                    <div class="col-md-6 offset-md-3">
                        <div class="col-sm-8 ">
                            <hr>
                            <div>
                                <p>{{ article.created_date }}</p>
                            </div>
                            <hr>
                            <div>
                                <p class="lead">{{ article.content|safe|truncatewords:10 }}</p>
                                <a style="float:right"
                                   href="/articles/article/{{ article.id }}"
                                   class="btn btn-danger">Devamini Oku</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container-fluid mt-3">
                    <div class="footer">
                        <footer>
                            <i class="fa-brands fa-google font m-2"></i>
                            <i class="fa-brands fa-youtube m-2 font "></i>
                            <i class="fa-brands fa-twitter m-2 font"></i>
                        </footer>
                    </div>
                </div>
            </body>
        </html>
    </div>
{% endfor %}
{% else %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
            <div class="alert alert-danger">Makale Bulunamadi</div>
        </div>
    </div>
</div>
{% endif %}
{% endblock  %}

blog/templates/dashboard.html
{% extends 'layout.html' %}
{% block body %}
    <h3>Kontrol Paneli</h3>
    <hr>
    <p>
        Hosgeldiniz,<small>{{ request.user.username }}</small>
    </p>
    <hr>
    <a class="btn btn-danger" href="/articles/addarticle">Makale Ekle</a>
    <hr>
    {% if articles %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">Baslik</th>
                    <th scope="col">Yazar</th>
                    <th scope="col">Tarih</th>
                    <th scope="col">Guncelle</th>
                    <th scope="col">Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <th scope="row">{{ article.id }}</th>
                        <td>
                            <a href="/articles/article/{{ article.id }}">{{ article.title }}</a>
                        </td>
                        <td>{{ article.author.username }}</td>
                        <td>{{ article.created_date }}</td>
                        <td>
                            <a href="/articles/update/{{ article.id }}" class="btn btn-danger">Guncelle</a>
                        </td>
                        <td>
                            <a href="/articles/delete/{{ article.id }}" class="btn btn-danger">Sil</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-danger">Henuz Bir Makaleniz Bulunmuyor...</div>
    {% endif %}
{% endblock body %}

blog/templates/detail.html
{% extends 'layout.html' %}
{% block body %}
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
            <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
            <title>Document</title>
            <link rel="stylesheet"
                  href="C:/Users/Intelpoint/Desktop/bootsrap/bootstrap.min.css.map">
            <link rel="stylesheet"
                  href="C:/Users/Intelpoint/Desktop/bootsrap/css/all.css">
            <link rel="stylesheet" href="C:/Users/Intelpoint/Desktop/bootsrap/blog.css">
        </head>
        <body>
            <div class="container">
                <div class="row border-bottom">
                    <div class="col-3">
                        <div class="col-lg-8">
                            <h3>
                                <i class="fa-solid fa-layer-group"></i>{{ article.title }}
                            </h3>
                            <hr>
                        </div>
                    </div>
                    <div class="col-3">
                        <h3 class="float-right">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </h3>
                    </div>
                </div>
            </div>
            <div class="container">
                <p class="lead">
                    by
                    {{ article.author.username }}
                </p>
                {% if article.article_image %}<img class="img-responsive"
     src="{{ article.article_image.url }}"
     alt="...">{% endif %}
            </div>
        </div>
    </div>
</div>
</div>
</div>
<div class="container mt-3">
    <div class="row">
        <div class="col-sm-8 ">
            <hr>
            <div>
                <p>{{ article.created_date }}</p>
            </div>
            <hr>
            <div>
                <p class="lead">{{ article.content|safe }}</p>
            </p>
            <hr>
            <h4>Yorumlar</h4>
            <hr>
            {% if comments %}
                {% for comment in comments %}
                    <div class="media mb-4">
                        <img class="d-flex mr-3 rounded-circle"
                             src="https://mail.google.com/mail/u/0?ui=2&ik=8c2455f534&attid=0.1&permmsgid=msg-f:1756721060660672803&th=1861207f46207923&view=att&disp=safe&realattid=1861207a5b8e3a741011"
                             alt="avatar"
                             width="65"
                             height="65">
                        <div class="media-body">
                            <h5 class="mt-0">{{ comment.comment_author }}</h5>
                            {{ comment.comment_date }}
                            <br>
                            {{ comment.comment_content }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-danger">Bu makaleye herhangi bir yorum yapilmamis,ilk yorumu yapan siz olun</div>
            {% endif %}
            <div class="card my-4">
                <h5 class="card-header">Yorum Ekle:</h5>
                <div class="card-body">
                    <form method="post" action="{% url 'comment' article.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">Isim</label>
                            <input type="text"
                                   class="form-control"
                                   id="formGroupExampleInput"
                                   name="comment_author"
                                   placeholder="Isminizi girin">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Yorum</label>
                            <textarea name="comment_content" class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-danger">Ekle</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="container-fluid mt-3">
    <div class="footer">
        <footer>
            <i class="fa-brands fa-google font m-2"></i>
            <i class="fa-brands fa-youtube m-2 font "></i>
            <i class="fa-brands fa-twitter m-2 font"></i>
        </footer>
    </div>
</div>
</body>
</html>
{% endblock  %}

blog/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a href="{% url 'index'%}" class="navbar-brand">Lelo</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{%url 'about'%}" class="nav-item nav-link active">Hakkinda</a>
                <a href="{%url 'articles'%}" class="nav-item nav-link active">Makaleler</a>
            </div>
            <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item active">
                <a href="{%url 'dashboard' %}" class="nav-link">Kontrol Paneli</a>
            </li>
            <li class="nav-item active">
                <a href="{%url 'user:logout'%}" class="nav-link">Cikis Yap</a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a href="{%url 'user:login'%}" class="nav-link">Giris Yap</a>
            </li>
            {% endif %}
            <li class="nav-item active">
                <a href="{% url 'user:register' %}" class="nav-link">Kayit Ol</a>
            </li>
        </ul>
        </div>
    </div>
</nav>

blog/templates/index.html
{% extends "layout.html" %}
{% block body %}
<div class="jumbotron text-center">
    <h3>Qaranliq dunyama xos geldiniz</h3>
    <p>Beynim qeder qarisiq bir mekan</p>
</div>
<p>
    {% if request.user.is_authenticated %}
          Giris Yapilmis, {{request.user.username}}
    {% else %}
          Giris Yapilmamis
    {% endif %}
</p>
{% endblock  %}

blog/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
    <title>LELO</title>
  </head>
  <body>
    {% include "includes/navbar.html" %}
    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
    <div style="margin-top: 50px; margin-bottom: 100px" class="container">
      {% block body %}{% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
  </body>
</html>

blog/templates/login.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giris Yap</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <br>
                <button type="submit" class="btn btn-danger">Giris Yap</button>
            </form>
        </div>
    </div>
{% endblock  %}

blog/templates/register.html
{% extends 'layout.html' %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayit Ol</h3>
        <hr>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Giris Yap</button>
        </form>
    </div>
  </div>
{% endblock  %}

blog/templates/update.html
{% extends 'layout.html' %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Guncelle</h3>
        <hr>
        <form method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Makale Guncelle</button>
        </form>
    </div>
  </div>
{% endblock body %}